### ISSUE TITLE
Task.3 Prepare an initial login page (test)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#13]
Code a basic/initial test page for the team to review, find areas of improvement and figure out how to proceed from there

Priority: High

Risk: Medium / will serve as our foundation or if we decide that it is not good enough, we can simply restart.

Done by: Yash, Fabio

**Comment by YashNathani0708** [comment]
After intense research , we conclude that react would be the best for the frontend technology. Made a Login page with react library.
