### ISSUE TITLE
Task.5 Add a footer in the UI 

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#15]
Include a footer in the UI that will show up on all pages if you scroll  all the way down to the bottom of the page (make sure it includes all the important information)

Priority: Low

Risk: low / the footer isn't the most important aspect of the app right now, so doing this later can be acceptable as there are more important things to do beforehand regarding the app

Done by: Yash, Fabio

**Comment by FabioKoshy** [comment]
The footer has been added to all pages and appears at the bottom, containing additional information and redirect links.

**Comment by YashNathani0708** [comment]
Added some css and fixed bugs. Made a responsive footer
