### ISSUE TITLE
US.6 Improve the login page

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#16]
Make small quality of life changes to the page that will make it look more appealing (ex: make the images and text in the header the same size)

Priority: Medium

Risk: medium / changes now can affect the future prototype so the changes cannot be done carelessly like the first try when it was just the initial test page

Done by: Yash, Fabio, Chris

**Comment by christophertna** [comment]
Some images were missing, the main Concordia logo picture was also missing from the navigation bar, the centering of some texts and sub-headers were not aligned properly, and more. All fixed by this point.

**Comment by YashNathani0708** [comment]
Update the UI/UX. Fixed some minor bugs
