### ISSUE TITLE
Task.7 Complete the backend of the app

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#17]
Integrate firebase (the backend) into the frontend of the app

Priority: High

Risk: high / if done incorrectly or poorly, the app will not function properly or may not function at all

Done by: Marcelo

**Comment by phmarcel0x** [comment]
Done!
Firebase auth. set up
Firestore db set up
Firebase rtdb set up (just in case)
