### ISSUE TITLE
Task.11 Make the authentication aspect (user login) of the app up and running (User acceptance test)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#21]
Make users such as students and instructors be able to login into their own respective pages

Priority: High

Risk: High / if not done properly, the app will not function at all and the the entire concept of the app will fall apart

Done by: Yash, Fabio, Marcelo

**Comment by phmarcel0x** [comment]
Done,
Instructors have a unique profile view
Students have a unique profile view

Specific views (content) coming soon.
