### ISSUE TITLE
US.14 Change the "Logout" button and set it as "Login" as the default for new users

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#23]
Ensure the "logout" and "login" buttons are shown at the appropriate pages

Priority: Low

Risk: Medium / we must ensure a user can successfully logout for security reasons.

Done by: Marcelo

**Comment by phmarcel0x** [comment]
Done, with small changes:
Log In => Sign In
Log Out => Sign Out
