### ISSUE TITLE
US.12 Test the authentication. (User testing the authentication with a good username and bad password, and again with a good password (User acceptance test))

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#31]
The user first tried to log in with a bad password, which the authentication rejected, and once again with the correct password, in which the authentication then accepted

Priority: High

Risk: High / If the authentication didn't work, we would've had to take a step back and look into our code to see what went wrong

**Comment by christophertna** [comment]
Tested with 2 student users and 1 instructor user.

**Comment by YashNathani0708** [comment]
Tested multiple times to find vulnerability

**Comment by christophertna** [comment]
Authentication correctly rejected the incorrect password combination for students
