### ISSUE TITLE
Us.16 Fix the small syntax and sentence structuring mistakes from the login page (user noticed minor english mistakes when looking navigating through the login page)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#33]
Simply correct some sentences that had some minor sentence and spelling mistakes on the login page

Priority: Low

Risk: Low / Not important to the functionality of the application, but for the formality

**Comment by christophertna** [comment]
Minor mistakes that were spotted and fixed in under 10 minutes.

**Comment by YashNathani0708** [comment]
Correct some minor spelling mistake in login page.
