### ISSUE TITLE
US.17 Implement a function that prevents students signing up as instructors (user suggested that they can impersonate an instructor as a student while trying to sign up)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#34]
Not a function that has to be included for Sprint 1, but definetly for later Sprints

Priority: Low

Risk: Low / If the function doesn't work, simply discard it and work on it later, as it is not required or necessary for this Sprint

**Comment by FabioKoshy** [comment]
To become an instructor, an Instructor key is created. This prevents any other user from registering as a instructor.
