### ISSUE TITLE
Task.18 Students should be able to create teams once they are logged in

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#35]
Students should be able to create teams (1 per student), and be able to join teams (1 per student as well). Students should also only be able to see their own group once they've logged in and joined a group

Priority: High 

Risk: High / An important function of the app is that students can form and join groups, if this function is not implemented, the app will lose a major part of its functionality

**Comment by YashNathani0708** [comment]
Added some css in studentDashborad and made responsive studentDashboard
