### ISSUE TITLE
Task.19 Instructors should be able to view and edit the student's group at will from their perspective

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#38]
Instructors should be able to form, remove, delete, edit and view student groups from their perspective. They can also confirm/approve once a group is full/completed

Priority: High

Risk: High / Instructors should have the ability to manipulate the student groups at will from their own perspective. If not, the process of forming groups will be chaotic

**Comment by YashNathani0708** [comment]
Mereged with firebase database to get data and display on real time ream on webpage

**Comment by FabioKoshy** [comment]
Objective accomplished
