### ISSUE TITLE
US.22 Students should be able to see a the full list of members of their team (user logged into their account after being assigned to a team by an instructor, but only saw himself on the team)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#39]
Students should be able to see the full list of team members once they've logged into their account on the application (if they have been assigned into a team)

Priority: High

Risk: High / Students not being able to see their team might cause confusion during the app's usage, so making sure they are able to see will improve clarity

**Comment by YashNathani0708** [comment]
Merged backend team creation logic with the frontend UI

**Comment by christophertna** [comment]
Initial version only let students see themselves in the team once they logged in

**Comment by FabioKoshy** [comment]
Updated the file so that student can see their team and other teams with their members.
