### ISSUE TITLE
US.23 Instructors's perspective on the login page is quite similar to the student's (user logged in a instructor, then as student, then pointed out many similarites)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#40]
Instructors' view should have a broader perspective on the students and class, as well as it should look a bit more formal (instructors should be able to see all team that have been created)

Priority: Medium

Risk: Medium / The perspective of the instructors being similar to the students won't affect the usage of the app, but might cause confusion during usage

**Comment by FabioKoshy** [comment]
While the UI is similar, instructors will find editing features only available to them. The intuitive UX makes navigation and task completion easy for all instructors, and the team table header color clearly differentiates between student and instructor perspectives.
