### ISSUE TITLE
US.24 Team creation and deletion not working (user couldn't create nor delete the teams as an instructor for some reason)

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#44]
Find and fix the coding error that prevents instructors from creating and deleting teams, an essential function for the instructors and for the application

Priority: Low

Risk: High / If the creation/deletion button does not work, it will heavily impact the team function of the app, an essential function of the whole application

**Comment by FabioKoshy** [comment]
The missing code has been implemented, and we are now ready for the Sprint 1 demo.
