### ISSUE TITLE
Task 1. Initial system prototype to allow students to evaluate who they want in their team

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#49]
The prototype shall demonstrate the ability for students to select any member within their own team to evaluate.

Story points: 13
Due date: 17/10/2024
Estimated time duration: 1 week
Priority: High
Risk: Low

Assignees: Marcelo, Evelynne

**Comment by christophertna** [comment]
The prototype should simply demonstrate the basic functioning of the new system requirement, it does not have to be perfect

**Comment by FabioKoshy** [comment]
The prototype has been developed
