### ISSUE TITLE
Task 2. Initial prototype of a feedback rating system

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#50]
The feedback prototype system shall allow the user to evaluate a peer based off of four specific criteria, with each allowing them a space to leave additional comments, totaling to a 5-point rating system. In short, a student shall  be able to select members to evaluate, select dimensions to evaluate, give peer rating on dimension and additionally provide optional comments for each evaluation criteria. 

Refer to the picture below for more details:

![GitHub issue 1](https://github.com/user-attachments/assets/1fc0215c-f4fa-4b4b-9893-37f4a3d3e671)

Story points: 13
Estimated time duration: 1 week
Due date: 17/10/2024
Priority: High
Risk: Low
Assignees: Evelyne, Marcelo

**Comment by christophertna** [comment]
The feedback rating system shall include a comment box where students can provide additional feedback if they want to (not requiring them to) for each evaluation criteria

**Comment by phmarcel0x** [comment]
On top of the required "Conceptual" & "Practical" Contribution and "Work Ethic" dimensions, we've added "Team Collaboration" and "Leadership", for a more comprehensive peer assessment.
