### ISSUE TITLE
Task 3. Organize the repository's branch structure

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#51]
The branch structure shall be clear for readers to view and understand what is going on in the repository. It shall also be organized and clear for the development team to easily identify things that they want to find.

Story points: 2
Estimated time duration: 2 hours
Due date: 25/10/2024
Priority: Low
Risk: Low
Assignees: Yash

**Comment by YashNathani0708** [comment]
We had a multiple branch that was not merged and unnecessary conflicted with main branch.
