### ISSUE TITLE
Task 4. Update the backend of the application

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#52]
The backend shall be updated in firebase to be able to support the new prototype feature that will allow students to select any student within the team to evaluate.

Story points: 8
Estimated time duration: 1 week
Due date: 17/10/2024
Priority: High
Risk: High
Assignee: Fabio

**Comment by FabioKoshy** [comment]
I have updated the firebase to support the new prototype
