### ISSUE TITLE
Task 5. Update the backend part 2

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#53]
The firebase backend shall be able to support the new feedback rating system, which will allow students to submit their evaluations of each other's contribution.

Story points: 8
Estimated time duration: 1 week
Due date: 17/10/2024
Priority: High
Risk: High
Assignee: Fabio

**Comment by phmarcel0x** [comment]
Firestore syncs immediately when a student submits a peer evaluation. Virtually no delay for an instructor to see the evaluation in their dashboard.
