### ISSUE TITLE
Task 6. Color-code the evaluation critera

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#54]
Each criteria shall be highlighted in a different color when hovered over with the user's mouse, to clarify the different evaluation criteria.

Story points: 3
Estimate time duration: 1 day
Due date: 25/10/2024
Priority: Low
Risk: Low
Assignees: Evelynne, Marcelo

**Comment by phmarcel0x** [comment]
UX is everything.
