### ISSUE TITLE
Task 7. Include the submit button 

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#55]
Once the confirmation page pops up, a button to confirm the submission titled "Submit" shall appear in the bottom center of the confirmation page, in which it will send the data back to firebase.

Story points: 8
Estimated time duration: 1 week
Due date: 25/10/2024
Priority: High
Risk: High
Assignees: Marcelo, Evelynne

**Comment by FabioKoshy** [comment]
Developed the submit button to work as intended and made sure the data gets stored in Firebase

**Comment by FabioKoshy** [comment]
Developed the submit button to work as intended and made sure the data gets stored in Firebase
