### ISSUE TITLE
Task 8. Include a function that checks if you completed all required sections when rating

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#56]
The function shall only pop up if and only if the user does not complete all the required fields during the assessment and will ask the user to complete them, then returning back to the assessment page to let the user continue where they left off.

Story points: 8
Estimated time duration: 1 week
Due date: 27/10/2024
Priority: Medium
Risk: Low
Assignees: Marcelo, Evelynne

**Comment by phmarcel0x** [comment]
Comment boxes remain optional. Dimension scores (1-5) are indeed mandatory before submitting.
