### ISSUE TITLE
User Story 9. Testing the feedback rating system

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#57]
User wanted to rate the team members, but had to rate the assessment criteria for each team member individually first. Would be much easier to give feedback completely (all assessments criteria) for each individual before moving on to the next member.

Goal: The system shall let the users rate all the criteria for a single individual before moving onto the next peer to be evaluated, and then evaluation all of their criteria.

Story points: 8
Estimated time duration: 1 week
Due date: 25/10/2024
Priority: High
Risk: Medium
Assignees: Chris, Marcelo, Evelynne

**Comment by christophertna** [comment]
This is the acceptance test for [User Story 9](https://github.com/phmarcel0x/Group12-SOEN341_Project_F24/issues/57#issue-2617004351).

User Acceptance Test (AT)
1. User logs in as a student 
2. User clicks a student within their team to evaluate
3. User rates the student by criteria and leaves additional feedback in the comment boxes below
4. User submits their feedback assessment by clicking the 'Submit' button from the confirmation page

**Comment by christophertna** [comment]
User also stated that it would be much easier to rate all of the criteria of an individual, one by one, instead of rating each individual's criteria, then moving onto the next criteria for each individual.

**Comment by phmarcel0x** [comment]
After discussing with team, users are to evaluate any student they choose (multiple allowed) criteria-by-criteria. The UX is simpler and demands less thinking than discussed alternatives.
