### ISSUE TITLE
Task 10. Replace all current students

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#58]
All newly created students shall be properly named and enumerated in a clear order, to avoid confusion when testing or demonstrating the application.

Story points: 8
Estimated time duration: 1 day
Due date: 25/10/2024
Priority: Medium
Risk: High
Assignees: Yash

**Comment by YashNathani0708** [comment]
Update the database with new entries of student. Removed the dummy entries.
