### ISSUE TITLE
Task 11. Update the firebase security rules

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#59]
The new security rules shall decrease the chances of the increased amount of data within the database being wiped out.

Story points: 5
Estimated time duration: 1 day
Due date: 25/10/2024
Priority: Medium
Risk: High
Assignees: Fabio

**Comment by FabioKoshy** [comment]
I have updated the Firebase security rules to prevent any leaks and the database from being wiped out.
