### ISSUE TITLE
Task 12. Calculate and display average scores for instructors

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#60]
The average shall be calculated by taking into account the points for each of the individual assessment criteria, and will be displayed only for the instructors to see, next to their name (the student's name).

Story points: 8
Estimated time duration: 1 week
Due date: 27/10/2024
Priority: High
Risk: High
Assignees: Marcelo, Evelynne

**Comment by phmarcel0x** [comment]
Instructor sees aggregate average of a student, given their peer's evaluations. Per dimension, and overall.
