### ISSUE TITLE
Task 13. Organize and upload all meeting minutes notes 

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#61]
The meeting minutes notes shall be organized and clear, as well as uploaded in the correct folder in the GitHub repository

Story points: 5
Estimated time duration: 1 week
Due date: 27/10/2024
Priority: High
Risk: High
Assignees: Tristan

**Comment by christophertna** [comment]
The meeting notes and the Sprint Plan 2 should be uploaded in the Sprint 2 folder, inside the main public folder

**Comment by tlepage1212** [comment]
All Meeting minutes have been uploaded in the public section of the code in GitHub
