### ISSUE TITLE
User Story 14. Testing as an instructor

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#62]
User logged in as an instructor, and wanted to see a team's individual scores for each member. The user had to individually look at each individual score by selecting each individual before getting access to their personal scores.

Goal: The instructor shall see an overview of all the team member's score, before deciding whether or not to individually select a particular student to view their score in more detail

Story points: 8
Estimated time duration: 1 week
Due date: 27/10/2024
Priority: Medium
Risk: Low
Assignees: Chris, Marcelo, Evelynne

**Comment by christophertna** [comment]
This is the acceptance test for [User Story 14.](https://github.com/phmarcel0x/Group12-SOEN341_Project_F24/issues/62#issue-2617072984)

User Acceptance Test (AT)
1. User logs in as an instructor
2. User selects a team to view their evaluation score
3. User selects an individual on the team to check their score
4. User gets shown the assessment criteria that was evaluated by their peer alongside the average score

**Comment by FabioKoshy** [comment]
Goal achieved
