### ISSUE TITLE
Task 15. Integrate the CI/CD pipeline in the repository

### ISSUE THREAD

**Issue by christophertna** [phmarcel0x/Group12-SOEN341_Project_F24#63]
The CI/CD pipeline shall be properly installed and integrated within the repository, to facilitate future code updates for future Sprints.

Story points: 8
Estimated time duration: 3 days
Due date: 27/10/2024
Priority: High
Risk: High
Assignees: Yash

**Comment by YashNathani0708** [comment]
Minor issue in CI/CD pipeline fixed
