### ISSUE TITLE
Task. 1 Format the data on the UI

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#71]
The data, including the calcualted grades and averages as well as the potential comments left by users shall be properly organized in a clean and orderly fashion forthe instructor to view from their perspective

Priority: Medium 

Risk: Medium / The formatting of the data won't affect the runtime or execution of the application and is a little UI change

**Comment by YashNathani0708** [comment]
Format the table's  data for better understanding
