### ISSUE TITLE
Task 2. Create two seperate instructor dashboards

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#72]
An instructor shall see a detailed dashboard of his class, including 2 new specific ways/formats to see the results of his class: either a detailed view of his class, or a summary view of his class

Priority: High

Risk: High / If done incorrectly, the instructor perspective will not be able to clearly view his class, as well as the application failing to meet an important system requirement

**Comment by FabioKoshy** [comment]
Created two dashboards with visualization graphs as the summary
