### ISSUE TITLE
US. 1 User logged in as an instructor. User was able to select their class for viewing. User saw the data for their class. User noted that the data shown was too "disorderly" and "messy".

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#73]
An instructor shall see a table of all his students with their specific information, including student ID, first and last name, team, individual evaluation points, the calculated average, as well as any comments left by feedback users

Priority: Medium

Risk: Medium / Clarity for the instructor will not severly impact the application

**Comment by christophertna** [comment]
The old UI (from previous sprint) wasn't bad, but definitely could have been improved in terms of organization and clarity

**Comment by FabioKoshy** [comment]
Updated the UI for better clarity and visualization.
