### ISSUE TITLE
US. 2 User logged in as a student. User saw their own grades that they received from the peer evaluation. User did  not agree with the grade they received and wanted to challenge/contest the grade, but had to email the instructor.

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#75]
A new contest feature shall be implemented from the student's perspective, where a student can contest a certain grade that they do not agree on, which will send a notification to the associated instructor of that student

Priority: High

Risk: High / A highly anticipated new required feature that will improve the quality of life for users

**Comment by FabioKoshy** [comment]
Worked with team to implement this feature.

**Comment by tlepage1212** [comment]
AT: Tested early versions of this feature and submitted feedback

**Comment by FabioKoshy** [comment]
Implemented Notification feature. Students can now challenge their grades, and instructors can see all notifications, the newest first. It also shows how many notifications you have and highlights the unread ones until you click on them.
