### ISSUE TITLE
US. 3 User logged in as an instructor. User saw the grades and averages by the students. User wanted a better visualisation of their class' grades

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#76]
The calculated data, such as the averages, shall also be displayed in graphical format for the instructors to see

Priority: Medium 

Risk: Medium / Will not affect the code, but is another required system enhancement that needs to be implemented

**Comment by christophertna** [comment]
New system feature that will help instructors visualize the grades of their class

**Comment by tlepage1212** [comment]
AT: Allows for easier visualization of the averages of the students

**Comment by FabioKoshy** [comment]
A Spider chart and a Bar chart is developed for better visualisation of their class grades
