### ISSUE TITLE
US. 1  User logged in as an instructor, but couldn't see if any of his students that contested their grades

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#82]
The instructor shall see a visual indicator next to the student's information if the said student decided to contest their grade

**Comment by tlepage1212** [comment]
Priority: High

**Comment by tlepage1212** [comment]
High / If not done, instructor will not be able to see if any of their students want to contest their grade, and has high potential of disrupting the code if done incorrectly

**Comment by christophertna** [comment]
The instructor dashboard should display a visual indicator (notification) next to the student's information on the list if that specific student contested their grade.

**Comment by FabioKoshy** [comment]
Developed a notification feature enabling instructors to view real-time updates regarding students contesting their grades.
