### ISSUE TITLE
Task. 1 Organize the repository 

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#83]
The repository structure shall follow the correct structure format (project files must be organized in packages/directories according to their intent)

**Comment by tlepage1212** [comment]
Priority: High

**Comment by tlepage1212** [comment]
Risk: High / If done incorrectly, the files will be disorganized and potentially lost

**Comment by YashNathani0708** [comment]
Organize all .css file to case-file and test.jsx to Test folder

**Comment by YashNathani0708** [comment]
Refactored the repository to adhere to a more organized and consistent structure. Moved all .css files to a dedicated styles folder and relocated test.jsx files to a tests folder. This improves maintainability and aligns with best practices for organizing project files based on their purpose.
