### ISSUE TITLE
Task. 2 Update the UI of the graphical visualizations of student grades

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#84]
The visualizations of student grades shall be more centered for easier viewing

**Comment by tlepage1212** [comment]
Priority: Low

**Comment by tlepage1212** [comment]
Risk: Low / A small quality of life change to view the grades easier as an instructor

**Comment by FabioKoshy** [comment]
The visualization of student grades has been implemented with a more centralized layout to enhance ease of viewing.

**Comment by lilevey** [comment]
Student grade visualization has been designed with a centralized layout to enhance viewing convenience.
