### ISSUE TITLE
Task. 3 Update the backend pt.1

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#86]
The firebase backend shall allow instructors to receive a notification about a student in their class contesting their grade

**Comment by tlepage1212** [comment]
Priority: High

**Comment by tlepage1212** [comment]
Risk: High / If the backend isn't completed succesfully, the instructor will not see any notification on their dashboard

**Comment by phmarcel0x** [comment]
Updated. Notification pop up when singing in as instructor. Summary of notifications on a right-hand tab.
