### ISSUE TITLE
US. 2 User logged in as an instructor. User wanted to see the feedback comments by a certain student. However, all comments from all students were displayed, and had to scroll alot before finding the exact comment.

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#87]
The instructor dashboard shall be formatted in a  way where if an instructor wants to read the comment by a student, they will have to click on a button  that says "See comment" to actually see the comment, instead of displaying all the students' comments at once

**Comment by tlepage1212** [comment]
Priority: Medium

**Comment by lilevey** [comment]
I implemented the feature where the instructor dashboard displays a ‘See comment’ button for each student, requiring instructors to click it to view individual comments instead of showing all comments at once

**Comment by phmarcel0x** [comment]
Enhancement almost finished, missing "comment" icon. Backend ready.
