### ISSUE TITLE
Task. 4 Implement an automatic repair tool to the repository

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#88]
The repository shall have SonarLint, an automatic repairing tool, properly installed and running

**Comment by tlepage1212** [comment]
Priority: High

**Comment by tlepage1212** [comment]
Risk: High / A required tool to be installed that will greatly help coding in the future

**Comment by FabioKoshy** [comment]
Integrated SonarQube, SonarLint, and ESLint to enhance code quality, provide real-time feedback, and identify potential issues effectively.
