### ISSUE TITLE
Task. 5 Student comments for grade contesting

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#89]
Students shall be able to type in a pop-up comment box after clicking on the grade contest button to further explain why they decided to contest their grade

**Comment by tlepage1212** [comment]
Priority: Medium

**Comment by tlepage1212** [comment]
Risk: Medium / A small but necessary quality of life change for students to further explain in detail their problem to the instructor about their grade

**Comment by phmarcel0x** [comment]
Good add-on. Done.
