### ISSUE TITLE
Task. 6 Update the backend pt.2

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#90]
The firebase backend shall allow instructors to see the comments of the students who  decided to contest their grade

**Comment by tlepage1212** [comment]
Priority: Medium

**Comment by tlepage1212** [comment]
Risk: Medium / The backend must be edited correctly to support the new feature

**Comment by phmarcel0x** [comment]
Backend ready to handle comments and hide them when not prompted to show. UI almost polished.
