### ISSUE TITLE
Task. 8  Organize and upload all necessary documentation

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#92]
All necessary documents shall be properly uploaded in the designated directory in the repository

**Comment by tlepage1212** [comment]
Priority: High

**Comment by tlepage1212** [comment]
Risk: High / All documentation needs to be on the repository before the deadline

**Comment by christophertna** [comment]
Meeting Minutes have been uploaded. Sprint Plan 4 will shortly be uploaded after all issues have been finalized.

**Comment by christophertna** [comment]
New Sprint 4 folder has been created under the _public_ folder. 
New text file to include Sprint 4 individual contribution logs under the  Sprint 4 folder has also been added.

**Comment by christophertna** [comment]
Including last minute changes and emergency issues to the Sprint Plan 4.

**Comment by christophertna** [comment]
Sprint Plan 4 has been officially uploaded.
