### ISSUE TITLE
Task. 9 New unit tests

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#93]
New proper unit tests shall be created in order to support the new features

**Comment by tlepage1212** [comment]
Priority: High

**Comment by tlepage1212** [comment]
Risk: High / Proper unit tests need to be created to test the new features of the app

**Comment by YashNathani0708** [comment]
Added multiple unit test cases to verify the functionality and rendering of the component. These tests ensure that the component behaves as expected under different scenarios, improving overall test coverage and confidence in its behavior.
