### ISSUE TITLE
Task. 10 CI/CD pipeline issue fix

### ISSUE THREAD

**Issue by tlepage1212** [phmarcel0x/Group12-SOEN341_Project_F24#94]
Fix a minor issue in the CI/CD pipeline which was preventing the installation of the automatic repair tool

**Comment by tlepage1212** [comment]
Priority: High

**Comment by YashNathani0708** [comment]
Ensured that dependencies are correctly installed and build steps run as expected. Pipeline now functions without errors during the installation process.
